<?= $this->extend('Frontend/layouts/main') ?>

<?= $this->section('content') ?>


<?= view_cell('\App\Libraries\Pages::breadcrumb', ['pagedata' => $pagedata]) ?>


<!-- MAIN CONTENT -->
<section class="section pt-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="postContent mt-4">

                    <p style="margin: 0in 0in 11.25pt; text-align: center;"><em><span style=" text-transform: uppercase;">Let&rsquo;s Scale Up welcomes you!</span></em></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>If you have any queries about Let&rsquo;s Scale Up, please do not hesitate to contact us. In this agreement, we have referred to the Let&rsquo;s Scale Up service as the "service", to you as the "user" and to our agreement as the "agreement".</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>If you wish to use our &ldquo;Common Needs&rdquo; feature, you affirm that you are more than 18 years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties consequent to the creation of the documents, and are aware of the same. Kindly contact us for further assistance.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">USER GUIDELINES</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The users of Let&rsquo;s Scale Up are granted a nonexclusive, limited right to access and use the service in accordance with the rules that are described in this contract. In order to keep this system attractive and useful for all users, it is important that users follow the rules of the system. Let&rsquo;s Scale Up reserves the right to deny further access to its service to any user who violates these rules, is the subject of complaints by other Let&rsquo;s Scale Up users or for any other reason.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Users engaged in any of the following activities on our system will not be tolerated:</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Foul or otherwise inappropriate language.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Racist, hateful, or otherwise offensive comments.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Promote or provide instructional information about illegal activities, or promoting physical harm or injury against any group or individual.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Defame any person or group which includes people of all ages, races, religions, and nationalities.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Violate the rights of another, including but not limited to the intellectual property rights of another. This includes using the service for acts of copyright, trademark, patent, trade secret, or other intellectual property infringement, including but not limited to offering pirated computer programs or links to such programs, information used to circumvent manufacturer-installed copy-protect devices, including serial or registration numbers for software programs, or any type of cracker utilities (this also includes files which are solely intended for game emulation).</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Violate Internet standards.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Use the service for displaying harassing, abusive, threatening, harmful, vulgar, obscene, or tortuous material or invading other's privacy.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Interfere with or disrupting the service or servers or networks connected to the service by posting advertisements or links to competing services, transmitting "junk mail", "spam", "chain letters", or unsolicited mass distribution of e-mail.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>✔</span><span> Compromise the security of the service Let&rsquo;s Scale Up provides. Please do not try to gain access to system areas private to Let&rsquo;s Scale Up, or to other users.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">DISCLAIMER OF INFORMATION OBTAINED ON THE SERVICE AND SOME USER SUPPLIED CONTENT</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>(a) Disclaimer of information obtained on the Service</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up provides lawyers and potential clients with a forum whereby people who need legal representation or help are connected to providers of it. Let&rsquo;s Scale Up is a resource for informational purposes and is intended, but not promised or guaranteed to be correct, complete, and up-to-date. The accuracy, completeness or adequacy of Let&rsquo;s Scale Up is not warranted or guaranteed. Let&rsquo;s Scale Up further assumes no liability for the interpretation and/or use of the information contained on this website. The owner of this website does not intend links from this site to other websites to be referrals to, endorsements of, or affiliations with the linked entities. Let&rsquo;s Scale Up is not responsible for, and makes no representations or warranties about the contents of websites to which links may be provided from this website.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up will make every effort to ensure that promotional material of a user trying to promote himself on the website is deleted. Apart from this, the opinions and views expressed are those of the individual users of the service and do not reflect those of Let&rsquo;s Scale Up. Data submitted by other users (lay persons) is not verified or reviewed in any way before it appears on the Let&rsquo;s Scale Up website. Please use due caution when using this site.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up makes every effort to verify that lawyers who subscribe to the service are licensed and in good standing with the local bar at the time of registration. However, Let&rsquo;s Scale Up cannot track, verify, or monitor the standing of lawyers using the Service. Therefore, Let&rsquo;s Scale Up makes no representation regarding the status, standing or ability of lawyers or law firm that is listed on the site.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Users are urged to make their own independent investigation and evaluation of lawyers or law firm being considered. The determination of the need for legal services and the choice of lawyers are extremely important decisions and should not be based solely on claims of expertise, or on the cost of rendering the requested legal services.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up is not responsible for, and in no way endorses any description or indication of specialization or limitation of practice by lawyers or law firm. Efforts will be made to avoid false information, but please be aware that no agency or board may have certified such lawyers as a specialists or experts in any indicated field of law practice. In addition, lawyers claiming specialization is not necessarily any more competent than other lawyers. It is up to the user to question the lawyers on the factual basis of any statement they make, ask for the names of the certifying agencies, and verify all information.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Users are encouraged to use caution when reviewing any information submitted by lawyers and other parties. Although Let&rsquo;s Scale Up requires lawyers to comply with all regulations governing lawyers conduct, it is impossible for Let&rsquo;s Scale Up to monitor lawyers' integrity.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up in no way endorses the content or legality of any offers, statements, or promises made by lawyers or any other parties, on or off this site.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>(b) Disclaimer of content supplied by users in the form of reviews, comments, communications, and other content</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>At various locations on the Site, Let&rsquo;s Scale Up may permit visitors to post reviews, comments, and other content (the "user content"). Let&rsquo;s Scale Up is not the publisher or author of such user content. It only stores and disseminates the ideas and opinions that Let&rsquo;s Scale Up members may choose to post and distribute as user content. Let&rsquo;s Scale Up disclaims all responsibility for this content. If any offending material is brought to the notice of Let&rsquo;s Scale Up, it will be deleted as soon as is possible. Whether such material is indeed offending will be finally be left to the discretion of Let&rsquo;s Scale Up.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">LIMITATIONS ON USE</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The contents of Let&rsquo;s Scale Up are for personal use only and not for commercial exploitation. You may not decompile, reverse engineer, disassemble, rent, lease, loan, sell, sublicense, or create derivative works from Let&rsquo;s Scale Up. Nor may you use any network monitoring or discovery software to determine the site architecture, or extract information about usage or users. You may not use any robot, spider, other automatic device, or manual process to monitor or copy the contents without taking prior written permission from Let&rsquo;s Scale Up. You may not copy, modify, reproduce, republish, distribute, display, or transmit for commercial, non-profit or public purposes all or any portion of Let&rsquo;s Scale Up, except to the extent permitted above. You may not use or otherwise export or re-export Let&rsquo;s Scale Up or any portion available on or through Let&rsquo;s Scale Up in violation of the export control laws and regulations of India. Any unauthorized use of Let&rsquo;s Scale Up or its content is prohibited.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">CONFIDENTIALITY</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up makes every effort to maintain the confidentiality of any information submitted by users to our system and our database of lawyers. The user is however warned that the use of the internet or e-mail for confidential or sensitive information is susceptible to risks that inevitably arise on this medium. Additionally, because Let&rsquo;s Scale Up cannot control the conduct of others, we cannot guarantee that this information will remain confidential. Please use caution in deciding what information to input into the System. Do not make any confessions or admissions. The user should preferably describe their issue or dispute in the general terms only. Specific information should only be revealed after the user has selected an advocate/lawyer/attorney and made contact outside the service (e.g. via telephone or appointment). Subscribing lawyers using this service should refrain from asking any user to reveal any specific or confidential information through the service. Let&rsquo;s Scale Up is not responsible for the release or improper use of such information by users or any release due to error or failure in the System.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">INDEMNIFICATION</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The user agrees that Let&rsquo;s Scale Up is not responsible for any harm that his/her use of this service may cause. The user agrees to indemnify, defend, and hold Let&rsquo;s Scale Up harmless from and against any and all liability and costs incurred in connection with any loss, liability, claim, demand, damage, and expenses arising from or in connection with the contents or use of the service. The user agrees that this defense and indemnity shall also apply to any breach by the user of the agreement or the foregoing representations, warranties and covenants. The user further agrees that this defense and indemnity shall include without limitation of lawyers&rsquo; fees and costs. The user also agrees that this defense and indemnity shall apply to Let&rsquo;s Scale Up, its founders, officers and employees. Let&rsquo;s Scale Up reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the user and the user shall not in any event settle any matter without the written consent of Let&rsquo;s Scale Up.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">COMMUNICATIONS AND OTHER DATA</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up is not responsible for any loss of data resulting from accidental or deliberate deletion, network or system outages, backup failure, file corruption, or any other reasons.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">LICENSE OF YOUR CONTENTS TO LET&rsquo;S SCALE UP</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>By uploading content to or submitting any materials for use on Let&rsquo;s Scale Up, you grant (or warrant that the owner of such rights has expressly granted) Let&rsquo;s Scale Up a perpetual, royalty-free, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from and distribute such materials or incorporate such materials into any form, medium, or technology now known or later developed. Let&rsquo;s Scale Up however gives an assurance that any information of a sensitive nature will not be intentionally disclosed and revealed to any third party.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">LET&rsquo;S SCALE UP PROPRIETARY RIGHTS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Except as expressly provided in these terms and conditions, nothing contained herein shall be construed as conferring any license or right, by implication, estoppels or otherwise, under copyright or other intellectual property rights. The user agrees that the content and Web Site are protected by copyright, trademark, service marks, patents or other proprietary rights and laws. The user acknowledges and agrees that the user is permitted to use this material and information only as expressly authorized by Let&rsquo;s Scale Up, and may not copy, reproduce, transmit, distribute, or create derivative works of such content or information without express authorization. The user acknowledges and agrees that Let&rsquo;s Scale Up can display images and text throughout the Service. Users cannot extract and publish any information from the system, either electronically or in print, without the permission of Let&rsquo;s Scale Up and the permission of all other concerned parties. This is not a complete list - other things on the system are also Let&rsquo;s Scale Up property. Contact Let&rsquo;s Scale Up before copying anything from the system with plans of reproducing it or distributing it.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">LINKING TO </span></strong><span><a style="color: blue; text-decoration: underline;" href="#"><strong><span style=" text-transform: uppercase;">LET&rsquo;S SCALE UP.in</span></strong></a></span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Users are welcome to provide links to the homepage of Let&rsquo;s Scale Up, provided they do not remove or obscure, by framing or otherwise, any portion of the homepage and that you discontinue providing links to the site if requested by Let&rsquo;s Scale Up.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">ADVERTISERS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up may contain advertising and sponsorship. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on Let&rsquo;s Scale Up is accurate and complies with applicable laws. Let&rsquo;s Scale Up will not be responsible for the illegality of or any error or inaccuracy in advertisers' or sponsors' materials.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">REGISTRATION</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Certain sections of Let&rsquo;s Scale Up may require you to register. If registration is requested, you agree to provide Let&rsquo;s Scale Up with accurate and complete registration information. It is your responsibility to inform Let&rsquo;s Scale Up of any changes to that information. Each registration is for a single person only, unless specifically designated otherwise on the registration page. Let&rsquo;s Scale Up does not permit a) any other person using the registered sections under your name; or b) access through a single name being made available to multiple users on a network. You are responsible for preventing such unauthorized use. If you believe there has been unauthorized use, please notify Let&rsquo;s Scale Up immediately by contacting us. If we find that unauthorized use is being made of Let&rsquo;s Scale Up and the services we provide, the right of any or many users may be terminated.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">ERRORS AND CORRECTIONS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up does not represent or warrant that the service will be error-free, free of viruses or other harmful components, or that defects will be corrected. Let&rsquo;s Scale Up may make improvements and/or changes to its features, functionality or service at any time.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">THIRD PARTY CONTENT</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Third party content may appear on Let&rsquo;s Scale Up or may be accessible via links from Let&rsquo;s Scale Up. Let&rsquo;s Scale Up is not responsible for and assumes no liability for any mistakes, misstatements of law, defamation, slander, libel, omissions, falsehood, obscenity or profanity in the statements, opinions, representations or any other form of information contained in any third-party content appearing on Let&rsquo;s Scale Up. You understand that the information and opinions in the third-party content is neither endorsed by nor does it reflect the belief of Let&rsquo;s Scale Up.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">UNLAWFUL ACTIVITY</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up reserves the right to investigate complaints or reported violations of the Agreement and to take any action Let&rsquo;s Scale Up deems appropriate including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">REMEDIES FOR VIOLATIONS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up reserves the right to seek all remedies available at law and in equity for violations of the Agreement, including but not limited to the right to block access from a particular Internet address to Let&rsquo;s Scale Up and its features.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">CONFLICTS CHECKS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The user understands that registered lawyers will not be able to and will not perform a check for conflicts of interest between the user and other clients of the registered lawyers prior to responding to a request. Conflict checks require the user to provide their name and contact information and the identity of any affiliated entities, opposing individuals and entities, and such other information as lawyers may require. Conflict checks by registered lawyers who obtains information from the user through this service are not possible since submissions by the user to subscribing lawyers are not sufficient to conduct such a check.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">SEVERABILITY OF PROVISIONS</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The Agreement and the Privacy Policy constitute the entire agreement with respect to the use of the service provided by Let&rsquo;s Scale Up. If any provision of these terms and conditions is unlawful, void or unenforceable then that provision shall be deemed severable from the remaining provisions and shall not affect their validity and enforceability.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">MODIFICATIONS TO TERMS OF USE</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up may change the agreement at any time. The user will be responsible for checking the Terms and Conditions before use. Use of the service after the change will indicate acceptance of the new terms and conditions.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">MODIFICATIONS TO SERVICE</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Let&rsquo;s Scale Up reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice to the user. The user agrees that Let&rsquo;s Scale Up shall not be liable to the user or any third party for any modification or discontinuance of the service. The user acknowledges and agrees that any termination of service under any provision of this agreement may be affected without prior notice, and acknowledges and agrees that Let&rsquo;s Scale Up may immediately delete data and files in the user's account and bar any further access to such files or the Service.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>A great danger for Let&rsquo;s Scale Up, and for all operators of online systems, is that we might be held accountable for the wrongful actions of our users. If one user libels another user, the injured user might blame us, even though the first user was really at fault. If a user uploads a program with a computer virus, and the other users' computers are damaged, we might be blamed even though a user left the virus on our System. If a user transmits illegal or improper information to another user, we might be blamed even though we did nothing more than unknowingly carry the message from one user to another. Accordingly, we need all users to accept responsibility for their own acts, and to accept that an act by another user that damages them must not be blamed on us, but only on the other user.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Although it is the goal of Let&rsquo;s Scale Up to provide users with reliable and quality systems, we may make mistakes or experience system failure from time to time. Such problems are inevitable in operating a system of this size. We would not be able to make this system available to users if we had to accept blame or financial liability for any usability problems, system failures or errors, or mistakes or damages of any kind. In order to continue offering and improving our service, Let&rsquo;s Scale Up must deny any warranties on this service and state that our liability for any problems connected with the use of our system is strictly limited.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>These needs are accomplished by the following disclaimers:</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><strong><span>(a) Disclaimer of Warranties</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The user expressly agrees that use of the service is at the user's sole risk. The service is provided on an "as is" and "as available" basis. Let&rsquo;s Scale Up expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. Let&rsquo;s Scale Up makes no warranty that the service will meet a user's requirements, that the service will be uninterrupted, timely, secure, or error-free; nor does Let&rsquo;s Scale Up make any warranty as to the results that may be obtained from the use of the service or as to the accuracy or reliability of any information obtained through the service or that defects in the software will be corrected. Let&rsquo;s Scale Up makes no warranty regarding any goods or services purchased or information obtained through the service or any transactions entered into through the service.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>No advice or information, whether oral or written, obtained by the User from Let&rsquo;s Scale Up shall create any warranty not expressly stated herein.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><strong><span>(b) Limitation of Liability</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>The user agrees that Let&rsquo;s Scale Up shall not be liable for any direct, indirect, incidental, special or consequential damages resulting from the use or the inability to use the service or for the cost of procurement of substitute goods and services or resulting from any goods or services purchased or obtained or messages received or transactions entered into through or from the service or resulting from unauthorized access to or alteration of user's transmissions or data, including, but not limited to damages for loss of profits, use, data or other intangibles, even if Let&rsquo;s Scale Up has been advised of the possibility of such damages. The user further agrees that Let&rsquo;s Scale Up shall not be liable for any damages arising from interruption, suspension or termination of service, including, but not limited to direct, indirect, incidental, special, consequential or exemplary damages, whether or not such interruption, suspension or termination was justified, negligent, intentional or inadvertent.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">ARBITRATION</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>Any controversy or claim arising out of or relating to this Agreement or Let&rsquo;s Scale Up services shall be settled by binding Arbitration in accordance with laws of India. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. Any other dispute or disagreement of a legal nature will also be decided in accordance with the laws of India, and the Courts of Delhi NCR shall have jurisdiction in all such cases.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">OWNERSHIP</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>This Site is owned and operated by Let&rsquo;s Scale Up. All right, title and interest in and to the materials provided on this Site, including but not limited to information, documents, logos, graphics, sounds and images (the "Materials") are owned by Let&rsquo;s Scale Up. Except as otherwise expressly provided by Let&rsquo;s Scale Up, none of the materials may be copied, reproduced, republished, downloaded, uploaded, posted, displayed, transmitted or distributed in any way and nothing on this Site shall be construed to confer any license under any of Let&rsquo;s Scale Up's intellectual property rights, whether by estoppel, implication or otherwise. Contact us if you have any questions about obtaining such licenses. Let&rsquo;s Scale Up does not sell, license, lease or otherwise provide any of the materials other than those specifically identified as being provided by Let&rsquo;s Scale Up. Any rights not expressly granted herein are reserved by Let&rsquo;s Scale Up.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">ENTIRE AGREEMENT</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>This agreement constitutes the entire and whole agreement between user and Let&rsquo;s Scale Up, and is intended as a complete and exclusive statement of the terms of the agreement. This agreement shall supersede all other communications between Let&rsquo;s Scale Up and its users with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. If at any time you find these Terms and Conditions unacceptable or if you do not agree to these Terms and Conditions, please do not use this Site. We may revise these Terms and Conditions at any time without notice to you. It is your responsibility to review these Terms and Conditions periodically.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>By using Let&rsquo;s Scale Up services or accessing the Let&rsquo;s Scale Up site, you acknowledge that you have read these terms and conditions and agree to be bound by them.</span></p>
                    <p style="margin: 0in 0in 11.25pt; text-align: justify;"><strong><span style=" text-transform: uppercase;">INDEMNIFICATION</span></strong></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>You agree to defend, indemnify and hold harmless Let&rsquo;s Scale Up, our officers, directors, shareholders, employees and agents from and against any and all claims, liabilities, damages, losses or expenses, including reasonable attorneys' fees and costs, arising out of or in any way connected with your access to or use of the site and the materials.</span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>We assure you that we are continuously working to improve our services and are we are welcome to any suggestions from your end. For any other queries please contact out customer service desk at&nbsp;</span><span><a style="color: blue; text-decoration: underline;" href="#"><span>Let&rsquo;s Scale Up.in.</span></a></span></p>
                    <p style="margin: 0in 0in 15pt; text-align: justify;"><span>CONTACT US </span></p>
                    <p style="text-align: justify; margin: 0in 0in 8pt; line-height: 107%;"><span style="line-height: 107%; ">Ph. No. <?= PHONE_NUMBER ?></span></p>
                    <p style="text-align: justify; margin: 0in 0in 8pt; line-height: 107%;"><span style="line-height: 107%; ">Email: </span><a style="color: blue; text-decoration: underline;" href="mailto:<?= GMAIL ?>"><span style="line-height: 107%; "><?= GMAIL ?></span></a></p>
                    <p style="text-align: justify; margin: 0in 0in 8pt; line-height: 107%;"><span style="line-height: 107%; ">Linked in: </span><a style="color: blue; text-decoration: underline;" href="https://www.linkedin.com/company/legaltech-india" aria-invalid="true"><span style="line-height: 107%; ">https://www.linkedin.com/company/legaltech-india</span></a><span style="line-height: 107%; "> </span></p>
                    <p style="text-align: justify; margin: 0in 0in 8pt; line-height: 107%;"><span style="line-height: 107%; ">Instagram: </span><a style="color: blue; text-decoration: underline;" href="https://instagram.com/lets_scale_up?igshid=1f4xs1cne1a6q"><span style="line-height: 107%; ">https://instagram.com/lets_scale_up?igshid=1f4xs1cne1a6q</span></a><span style="line-height: 107%; "> </span></p>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- MAIN CONTENT -->

<style>
    .postContent {
        max-width: 800px;
        margin: 0 auto;
    }
</style>

<?= $this->endSection() ?>